BILL_SCHEMA = {
    "consumer_name": "string",
    "reference_number": "string",
    "billing_month": "string",
    "units_consumed": "number",
    "tariff_category": "string",
    "protected_status": "string",
    "phase": "string",
    "energy_charges": "number",
    "fpa": "number",
    "qta": "number",
    "gst": "number",
    "electricity_duty": "number",
    "tv_fee": "number",
    "subsidies": "number",
    "net_electricity_charges": "number",
    "gross_total": "number",
    "total_amount_due": "number",
    "due_date": "string",
}